#ifndef LAUNCH_TASK_N_PARSER_H
#define LAUNCH_TASK_N_PARSER_H
#include <QStringList>
#include <QDebug>
#include <Qprocess>
#include <QString>
#include <QStandardPaths>
#include <QDesktopServices>
#include <QUrl>
#include <QDir>
QString defver = "1.21.5";
QString mcpath = ".minecraft";
QString verpath = mcpath + "\\versions\\" + defver + "\\" + defver + ".jar";
QProcess executemc = QProcess();
QString username;
QString assetdir = mcpath + "\\assets";
QString natdir = mcpath + "\\versions\\" + defver + "\\natives";
QStringList jvmargs = QStringList();
QStringList gameargs = QStringList();
QProcess mcprocess;
//1.21.5 classpath (and some trash)
QStringList classpath = {
    mcpath + "\\libraries\\com\\mojang\\blocklist\\1.0.10\\blocklist-1.0.10.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl\\lwjgl-platform\\2.9.4-nightly-20150209\\lwjgl-platform-2.9.4-nightly-20150209.jar",
    mcpath + "\\libraries\\ru\\tln4\\empty\\0.1\\empty-0.1.jar",
    mcpath + "\\libraries\\it\\unimi\\dsi\\fastutil\\8.5.15\\fastutil-8.5.15.jar",
    mcpath + "\\libraries\\com\\ibm\\icu\\icu4j\\76.1\\icu4j-76.1.jar",
    mcpath + "\\libraries\\com\\mojang\\realms\\1.10.22\\realms-1.10.22.jar",
    mcpath + "\\libraries\\com\\github\\usefulness\\webp-imageio\\0.8.0\\webp-imageio-0.8.0.jar",
    mcpath + "\\libraries\\com\\google\\guava\\guava\\33.3.1-jre\\guava-33.3.1-jre.jar",
    mcpath + "\\libraries\\org\\jetbrains\\kotlin\\kotlin-reflect\\2.0.0\\kotlin-reflect-2.0.0.jar",
    mcpath + "\\libraries\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar",
    mcpath + "\\libraries\\com\\google\\guava\\guava\\17.0\\guava-17.0.jar",
    mcpath + "\\libraries\\net\\java\\dev\\jna\\jna\\5.15.0\\jna-5.15.0.jar",
    mcpath + "\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.24.1\\log4j-core-2.24.1.jar",
    mcpath + "\\libraries\\org\\jetbrains\\kotlin\\kotlin-stdlib\\2.0.0\\kotlin-stdlib-2.0.0.jar",
    mcpath + "\\libraries\\com\\ibm\\icu\\icu4j-core-mojang\\51.2\\icu4j-core-mojang-51.2.jar",
    mcpath + "\\libraries\\com\\fasterxml\\jackson\\core\\jackson-databind\\2.13.4.2\\jackson-databind-2.13.4.2.jar",
    mcpath + "\\libraries\\net\\fabricmc\\sponge-mixin\\0.15.5+mixin.0.8.7\\sponge-mixin-0.15.5+mixin.0.8.7.jar",
    mcpath + "\\libraries\\net\\fabricmc\\fabric-loader\\0.16.14\\fabric-loader-0.16.14.jar",
    mcpath + "\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.8.1\\log4j-core-2.8.1.jar",
    mcpath + "\\libraries\\net\\java\\dev\\jna\\jna-platform\\5.15.0\\jna-platform-5.15.0.jar",
    mcpath + "\\libraries\\ca\\weblite\\java-objc-bridge\\1.1\\java-objc-bridge-1.1.jar",
    mcpath + "\\libraries\\net\\java\\dev\\jna\\jna\\4.4.0\\jna-4.4.0.jar",
    mcpath + "\\libraries\\org\\apache\\commons\\commons-compress\\1.27.1\\commons-compress-1.27.1.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl\\2.9.4-nightly-20150209\\lwjgl-2.9.4-nightly-20150209.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-freetype\\3.3.3\\lwjgl-freetype-3.3.3-natives-windows.jar",
    mcpath + "\\libraries\\org\\jitsi\\jain-sip-ri-ossonly\\1.2.279-jitsi-oss1\\jain-sip-ri-ossonly-1.2.279-jitsi-oss1.jar",
    mcpath + "\\libraries\\net\\java\\dev\\jna\\jna\\3.4.0\\jna-3.4.0.jar",
    mcpath + "\\libraries\\com\\github\\oshi\\oshi-core\\6.6.5\\oshi-core-6.6.5.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.3\\lwjgl-opengl-3.3.3.jar",
    mcpath + "\\libraries\\net\\java\\dev\\jna\\platform\\3.4.0\\platform-3.4.0.jar",
    mcpath + "\\libraries\\com\\nimbusds\\oauth2-oidc-sdk\\11.18\\oauth2-oidc-sdk-11.18.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-freetype\\3.3.3\\lwjgl-freetype-3.3.3-natives-windows-arm64.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-freetype\\3.3.3\\lwjgl-freetype-3.3.3-natives-windows-x86.jar",
    mcpath + "\\libraries\\com\\nimbusds\\nimbus-jose-jwt\\9.40\\nimbus-jose-jwt-9.40.jar",
    mcpath + "\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.5.14\\httpclient-4.5.14.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl\\3.3.3\\lwjgl-3.3.3.jar",
    mcpath + "\\libraries\\org\\joml\\joml\\1.10.8\\joml-1.10.8.jar",
    mcpath + "\\libraries\\net\\fabricmc\\intermediary\\1.21.5\\intermediary-1.21.5.jar",
    mcpath + "\\libraries\\com\\mojang\\datafixerupper\\8.0.16\\datafixerupper-8.0.16.jar",
    mcpath + "\\libraries\\io\\netty\\netty-common\\4.1.118.Final\\netty-common-4.1.118.Final.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.3\\lwjgl-openal-3.3.3-natives-windows.jar",
    mcpath + "\\libraries\\org\\lz4\\lz4-java\\1.8.0\\lz4-java-1.8.0.jar",
    mcpath + "\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.0-beta9\\log4j-core-2.0-beta9.jar",
    mcpath + "\\libraries\\org\\apache\\commons\\commons-lang3\\3.17.0\\commons-lang3-3.17.0.jar",
    mcpath + "\\libraries\\io\\sentry\\sentry\\6.13.0\\sentry-6.13.0.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.3\\lwjgl-openal-3.3.3-natives-windows-x86.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.3\\lwjgl-openal-3.3.3-natives-windows-arm64.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl\\lwjgl-platform\\2.9.4-nightly-20150209\\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar",
    mcpath + "\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.3.3\\httpclient-4.3.3.jar",
    mcpath + "\\libraries\\io\\netty\\netty-handler\\4.1.118.Final\\netty-handler-4.1.118.Final.jar",
    mcpath + "\\libraries\\io\\netty\\netty-transport\\4.1.118.Final\\netty-transport-4.1.118.Final.jar",
    mcpath + "\\libraries\\commons-io\\commons-io\\2.17.0\\commons-io-2.17.0.jar",
    mcpath + "\\libraries\\org\\jitsi\\ice4j\\3.0-68-gd289f12\\ice4j-3.0-68-gd289f12.jar",
    mcpath + "\\libraries\\org\\apache\\commons\\commons-lang3\\3.5\\commons-lang3-3.5.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-freetype\\3.3.3\\lwjgl-freetype-3.3.3.jar",
    mcpath + "\\libraries\\org\\apache\\commons\\commons-lang3\\3.3.2\\commons-lang3-3.3.2.jar",
    mcpath + "\\libraries\\com\\fasterxml\\jackson\\core\\jackson-core\\2.13.4\\jackson-core-2.13.4.jar",
    mcpath + "\\libraries\\commons-codec\\commons-codec\\1.17.1\\commons-codec-1.17.1.jar",
    mcpath + "\\libraries\\com\\microsoft\\azure\\msal4j\\1.17.2\\msal4j-1.17.2.jar",
    mcpath + "\\libraries\\org\\apache\\commons\\commons-compress\\1.8.1\\commons-compress-1.8.1.jar",
    mcpath + "\\libraries\\io\\netty\\netty-codec\\4.1.118.Final\\netty-codec-4.1.118.Final.jar",
    mcpath + "\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.24.1\\log4j-api-2.24.1.jar",
    mcpath + "\\libraries\\io\\netty\\netty-buffer\\4.1.118.Final\\netty-buffer-4.1.118.Final.jar",
    mcpath + "\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.4.16\\httpcore-4.4.16.jar",
    mcpath + "\\libraries\\com\\google\\code\\gson\\gson\\2.11.0\\gson-2.11.0.jar",
    mcpath + "\\libraries\\com\\typesafe\\config\\1.4.2\\config-1.4.2.jar",
    mcpath + "\\libraries\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar",
    mcpath + "\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.3.2\\httpcore-4.3.2.jar",
    mcpath + "\\libraries\\commons-codec\\commons-codec\\1.9\\commons-codec-1.9.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.3\\lwjgl-stb-3.3.3-natives-windows.jar",
    mcpath + "\\libraries\\com\\google\\code\\gson\\gson\\2.8.0\\gson-2.8.0.jar",
    mcpath + "\\libraries\\org\\junit\\jupiter\\junit-jupiter-engine\\5.8.2\\junit-jupiter-engine-5.8.2.jar",
    mcpath + "\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.8.1\\log4j-api-2.8.1.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.3\\lwjgl-stb-3.3.3-natives-windows-x86.jar",
    mcpath + "\\libraries\\org\\checkerframework\\checker-qual\\3.33.0\\checker-qual-3.33.0.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.3\\lwjgl-stb-3.3.3-natives-windows-arm64.jar",
    mcpath + "\\libraries\\commons-io\\commons-io\\2.5\\commons-io-2.5.jar",
    mcpath + "\\libraries\\net\\java\\jinput\\jinput\\2.0.5\\jinput-2.0.5.jar",
    mcpath + "\\libraries\\io\\github\\llamalad7\\mixinextras-common\\0.4.1\\mixinextras-common-0.4.1.jar",
    mcpath + "\\libraries\\org\\junit\\jupiter\\junit-jupiter-api\\5.8.2\\junit-jupiter-api-5.8.2.jar",
    mcpath + "\\libraries\\com\\google\\code\\gson\\gson\\2.2.4\\gson-2.2.4.jar",
    mcpath + "\\libraries\\com\\mojang\\jtracy\\1.0.29\\jtracy-1.0.29-natives-linux.jar",
    mcpath + "\\libraries\\org\\junit\\platform\\junit-platform-engine\\1.8.2\\junit-platform-engine-1.8.2.jar",
    mcpath + "\\libraries\\commons-io\\commons-io\\2.4\\commons-io-2.4.jar",
    mcpath + "\\libraries\\org\\jitsi\\jitsi-utils\\1.0-127-g6c65524\\jitsi-utils-1.0-127-g6c65524.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.3\\lwjgl-jemalloc-3.3.3-natives-windows.jar",
    mcpath + "\\libraries\\com\\mojang\\jtracy\\1.0.29\\jtracy-1.0.29-natives-macos.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl\\lwjgl_util\\2.9.4-nightly-20150209\\lwjgl_util-2.9.4-nightly-20150209.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.3\\lwjgl-glfw-3.3.3-natives-windows.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl\\3.3.3\\lwjgl-3.3.3-natives-windows.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.3\\lwjgl-glfw-3.3.3-natives-windows-x86.jar",
    mcpath + "\\libraries\\net\\java\\jinput\\jinput-platform\\2.0.5\\jinput-platform-2.0.5-natives-windows.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.3\\lwjgl-jemalloc-3.3.3-natives-windows-arm64.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.3\\lwjgl-jemalloc-3.3.3-natives-windows-x86.jar",
    mcpath + "\\libraries\\io\\netty\\netty-transport-classes-epoll\\4.1.118.Final\\netty-transport-classes-epoll-4.1.118.Final.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.3\\lwjgl-glfw-3.3.3-natives-windows-arm64.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl\\3.3.3\\lwjgl-3.3.3-natives-windows-x86.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.3\\lwjgl-glfw-3.3.3.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl\\3.3.3\\lwjgl-3.3.3-natives-windows-arm64.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.3\\lwjgl-tinyfd-3.3.3-natives-windows.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm\\9.8\\asm-9.8.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm\\9.7\\asm-9.7.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm\\9.6\\asm-9.6.jar",
    mcpath + "\\libraries\\net\\minidev\\json-smart\\2.5.1\\json-smart-2.5.1.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.3\\lwjgl-stb-3.3.3.jar",
    mcpath + "\\libraries\\com\\mojang\\authlib\\6.0.58\\authlib-6.0.58.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.3\\lwjgl-tinyfd-3.3.3-natives-windows-x86.jar",
    mcpath + "\\libraries\\com\\google\\auto\\auto-common\\1.2.1\\auto-common-1.2.1.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.3\\lwjgl-tinyfd-3.3.3-natives-windows-arm64.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.3\\lwjgl-openal-3.3.3.jar",
    mcpath + "\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.0-beta9\\log4j-api-2.0-beta9.jar",
    mcpath + "\\libraries\\com\\squareup\\javapoet\\1.13.0\\javapoet-1.13.0.jar",
    mcpath + "\\libraries\\com\\paulscode\\codecjorbis\\20101023\\codecjorbis-20101023.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.3\\lwjgl-opengl-3.3.3-natives-windows.jar",
    mcpath + "\\libraries\\org\\junit\\platform\\junit-platform-commons\\1.8.2\\junit-platform-commons-1.8.2.jar",
    mcpath + "\\libraries\\org\\jcraft\\jorbis\\0.0.17\\jorbis-0.0.17.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm-util\\9.8\\asm-util-9.8.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm-util\\9.7\\asm-util-9.7.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.3\\lwjgl-opengl-3.3.3-natives-windows-x86.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.3\\lwjgl-opengl-3.3.3-natives-windows-arm64.jar",
    mcpath + "\\libraries\\org\\jitsi\\jitsi-metaconfig\\1.0-9-g5e1b624\\jitsi-metaconfig-1.0-9-g5e1b624.jar",
    mcpath + "\\libraries\\com\\mojang\\text2speech\\1.10.3\\text2speech-1.10.3-natives-windows.jar",
    mcpath + "\\libraries\\com\\mojang\\brigadier\\1.3.10\\brigadier-1.3.10.jar",
    mcpath + "\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.3\\jopt-simple-5.0.3.jar",
    mcpath + "\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.4\\jopt-simple-5.0.4.jar",
    mcpath + "\\libraries\\com\\fasterxml\\jackson\\core\\jackson-annotations\\2.13.4\\jackson-annotations-2.13.4.jar",
    mcpath + "\\libraries\\commons-logging\\commons-logging\\1.3.4\\commons-logging-1.3.4.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm-commons\\9.8\\asm-commons-9.8.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm-commons\\9.7\\asm-commons-9.7.jar",
    mcpath + "\\libraries\\net\\minecraftforge\\srgutils\\0.5.4\\srgutils-0.5.4.jar",
    mcpath + "\\libraries\\org\\slf4j\\slf4j-api\\2.0.16\\slf4j-api-2.0.16.jar",
    mcpath + "\\libraries\\com\\github\\vatbub\\mslinks\\1.0.6.2\\mslinks-1.0.6.2.jar",
    mcpath + "\\libraries\\com\\mojang\\authlib\\1.5.25\\authlib-1.5.25.jar",
    mcpath + "\\libraries\\com\\paulscode\\soundsystem\\20120107\\soundsystem-20120107.jar",
    mcpath + "\\libraries\\com\\mojang\\authlib\\1.5.21\\authlib-1.5.21.jar",
    mcpath + "\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\4.6\\jopt-simple-4.6.jar",
    mcpath + "\\libraries\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm-tree\\9.7\\asm-tree-9.7.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm-tree\\9.8\\asm-tree-9.8.jar",
    mcpath + "\\libraries\\com\\mojang\\jtracy\\1.0.29\\jtracy-1.0.29-natives-windows.jar",
    mcpath + "\\libraries\\org\\jitsi\\jicoco-config\\1.1-127-gf49982f\\jicoco-config-1.1-127-gf49982f.jar",
    mcpath + "\\libraries\\io\\netty\\netty-transport-native-unix-common\\4.1.118.Final\\netty-transport-native-unix-common-4.1.118.Final.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.3\\lwjgl-jemalloc-3.3.3.jar",
    mcpath + "\\libraries\\io\\netty\\netty-transport-native-epoll\\4.1.118.Final\\netty-transport-native-epoll-4.1.118.Final-linux-aarch_64.jar",
    mcpath + "\\libraries\\io\\netty\\netty-transport-native-epoll\\4.1.118.Final\\netty-transport-native-epoll-4.1.118.Final-linux-x86_64.jar",
    mcpath + "\\libraries\\io\\netty\\netty-resolver\\4.1.118.Final\\netty-resolver-4.1.118.Final.jar",
    mcpath + "\\libraries\\net\\minecraft\\launchwrapper\\3.2.1\\launchwrapper-3.2.1.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm-analysis\\9.8\\asm-analysis-9.8.jar",
    mcpath + "\\libraries\\org\\ow2\\asm\\asm-analysis\\9.7\\asm-analysis-9.7.jar",
    mcpath + "\\libraries\\oshi-project\\oshi-core\\1.1\\oshi-core-1.1.jar",
    mcpath + "\\libraries\\org\\jetbrains\\annotations\\24.0.1\\annotations-24.0.1.jar",
    mcpath + "\\libraries\\net\\minidev\\accessors-smart\\2.5.1\\accessors-smart-2.5.1.jar",
    mcpath + "\\libraries\\org\\apache\\logging\\log4j\\log4j-slf4j2-impl\\2.24.1\\log4j-slf4j2-impl-2.24.1.jar",
    mcpath + "\\libraries\\org\\bitlet\\weupnp\\0.1.4\\weupnp-0.1.4.jar",
    mcpath + "\\libraries\\javax\\annotation\\javax.annotation-api\\1.3.2\\javax.annotation-api-1.3.2.jar",
    mcpath + "\\libraries\\com\\googlecode\\json-simple\\json-simple\\1.1.1\\json-simple-1.1.1.jar",
    mcpath + "\\libraries\\com\\mojang\\patchy\\2.2.10\\patchy-2.2.10.jar",
    mcpath + "\\libraries\\com\\paulscode\\libraryjavasound\\20101123\\libraryjavasound-20101123.jar",
    mcpath + "\\libraries\\com\\google\\code\\findbugs\\jsr305\\3.0.2\\jsr305-3.0.2.jar",
    mcpath + "\\libraries\\com\\mojang\\logging\\1.5.10\\logging-1.5.10.jar",
    mcpath + "\\libraries\\com\\google\\errorprone\\error_prone_annotations\\2.27.0\\error_prone_annotations-2.27.0.jar",
    mcpath + "\\libraries\\com\\paulscode\\librarylwjglopenal\\20100824\\librarylwjglopenal-20100824.jar",
    mcpath + "\\libraries\\org\\opentelecoms\\sdp\\sdp-api\\1.0\\sdp-api-1.0.jar",
    mcpath + "\\libraries\\com\\mojang\\text2speech\\1.18.11\\text2speech-1.18.11.jar",
    mcpath + "\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.3\\lwjgl-tinyfd-3.3.3.jar",
    mcpath + "\\libraries\\pt\\davidafsilva\\apple\\jkeychain\\1.1.0\\jkeychain-1.1.0.jar",
    mcpath + "\\libraries\\com\\google\\auto\\service\\auto-service\\1.1.1\\auto-service-1.1.1.jar",
    mcpath + "\\libraries\\com\\turikhay\\ca-fixer\\1.0\\ca-fixer-1.0.jar",
    mcpath + "\\libraries\\com\\nimbusds\\lang-tag\\1.7\\lang-tag-1.7.jar",
    mcpath + "\\libraries\\com\\mojang\\text2speech\\1.10.3\\text2speech-1.10.3.jar",
    mcpath + "\\libraries\\com\\mojang\\jtracy\\1.0.29\\jtracy-1.0.29.jar",
    mcpath + "\\libraries\\net\\neoforged\\installertools\\cli-utils\\2.1.2\\cli-utils-2.1.2.jar",
    mcpath + "\\libraries\\com\\google\\j2objc\\j2objc-annotations\\2.8\\j2objc-annotations-2.8.jar",
    mcpath + "\\libraries\\com\\nimbusds\\content-type\\2.3\\content-type-2.3.jar",
    mcpath + "\\libraries\\org\\opentelecoms\\sdp\\java-sdp-nist-bridge\\1.2\\java-sdp-nist-bridge-1.2.jar",
    mcpath + "\\libraries\\org\\opentest4j\\opentest4j\\1.2.0\\opentest4j-1.2.0.jar",
    mcpath + "\\libraries\\net\\java\\jutils\\jutils\\1.0.0\\jutils-1.0.0.jar",
    mcpath + "\\libraries\\net\\neoforged\\javadoctor\\gson-io\\2.0.0\\gson-io-2.0.0.jar",
    mcpath + "\\libraries\\com\\paulscode\\codecwav\\20101023\\codecwav-20101023.jar",
    mcpath + "\\libraries\\com\\google\\guava\\failureaccess\\1.0.2\\failureaccess-1.0.2.jar",
    mcpath + "\\libraries\\com\\github\\stephenc\\jcip\\jcip-annotations\\1.0-1\\jcip-annotations-1.0-1.jar",
    mcpath + "\\libraries\\aopalliance\\aopalliance\\1.0\\aopalliance-1.0.jar",
    mcpath + "\\libraries\\com\\mojang\\patchy\\2.2.10\\patchy-2.2.10.jar",
    mcpath + "\\libraries\\com\\google\\auto\\service\\auto-service-annotations\\1.1.1\\auto-service-annotations-1.1.1.jar",
    mcpath + "\\libraries\\javax\\inject\\javax.inject\\1\\javax.inject-1.jar",
    mcpath + "\\libraries\\com\\google\\guava\\listenablefuture\\9999.0-empty-to-avoid-conflict-with-guava\\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar",
    verpath};
bool it_has_username = false;
//i hate this
QString no_username_text = "There's no username created. Please create one";
QString username_created = "Username created: ";
QString username_is_empty = "Username is empty. Please create one";
QString process_err_str = "The process could not start: ";
QString err_when_reading_file = "Error when reading file.";

#endif
